// src/app/src/components/Home.vue
<template lang="pug">
md-content(role='main').mpj-main-content
  page-title(title='Welcome!'
             hideOnPage=true)
  p &nbsp;
  p.
    myPrayerJournal is a place where individuals can record their prayer requests, record that they prayed for them,
    update them as God moves in the situation, and record a final answer received on that request. It also allows
    individuals to review their answered prayers.
  p.
    This site is open and available to the general public. To get started, simply click the &ldquo;Log On&rdquo; link
    above, and log on with either a Microsoft or Google account. You can also learn more about the site at the
    &ldquo;Docs&rdquo; link, also above.
</template>

<script>
'use strict'

export default {
  name: 'home'
}
</script>

// src/my-prayer-journal/src/app/pages/home/home.component.ts
import { Component } from '@angular/core'

/**
 * Home Page.
 * 
 * @author Daniel J. Summers <daniel@bitbadger.solutions>
 * @version 3
 */
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html'
})
export class HomeComponent {
  constructor() { }
}

<main role="main" class="mpj-main-content">
  <p>&nbsp;</p>
  <p>
    myPrayerJournal is a place where individuals can record their prayer requests, record that they prayed for them,
    update them as God moves in the situation, and record a final answer received on that request. It also allows
    individuals to review their answered prayers.
  </p>
  <p>
    This site is open and available to the general public. To get started, simply click the &ldquo;Log On&rdquo; link
    above, and log on with either a Microsoft or Google account. You can also learn more about the site at the
    &ldquo;Docs&rdquo; link, also above.
  </p>
</main>
