// src/my-prayer-journal/src/app/shared/ui/navigation/navigation.component.ts
import { Component } from '@angular/core'
import { AuthService } from 'src/app/auth.service'

/**
 * myPrayerJournal Navigation.
 * 
 * @author Daniel J. Summers <daniel@bitbadger.solutions>
 * @version 3
 */
@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.sass']
})
export class NavigationComponent {

  // TODO: get this from the store's state
  hasSnoozed = false

  constructor(public auth: AuthService) { }

  /**
   * Start the log on process.
   * 
   * @param e The click event (used to stop the default action)
   */
  logOn(e: Event) {
    e.preventDefault()
    this.auth.login()
  }

  /**
   * Log the user off.
   * 
   * @param e The click event (used to stop the default action)
   */
  logOff(e: Event) {
    e.preventDefault()
    this.auth.logout()
  }
}

<ng-container *ngIf="auth.loggedIn">
  <a routerLink="/journal">Journal</a>
  <a routerLink="/requests/active">Active</a>
  <a *ngIf="hasSnoozed" routerLink="/requests/snoozed">Snoozed</a>
  <a routerLink="/requests/answered">Answered</a>
  <a href="/user/log-off" (click)="logOff($event)">Log Off</a>
</ng-container>
<a *ngIf="!auth.loggedIn" href="/user/log-on" (click)="logOn($event)">Log On</a>
<a href="https://docs.prayerjournal.me" target="_blank">Docs</a>

// src/app/src/components/common/Navigation.vue
<template lang="pug">
.md-toolbar-row
  md-tabs(md-sync-route).md-primary
    md-tab(v-if='isAuthenticated'
           md-label='Journal'
           to='/journal')
    md-tab(v-if='isAuthenticated'
           md-label='Active'
           to='/requests/active')
    md-tab(v-if='hasSnoozed'
           md-label='Snoozed'
           to='/requests/snoozed')
    md-tab(v-if='isAuthenticated'
           md-label='Answered'
           to='/requests/answered')
    md-tab(v-if='isAuthenticated'
           md-label='Log Off'
           href='#'
           @click.stop='logOff()')
    md-tab(v-if='!isAuthenticated'
           md-label='Log On'
           href='#'
           @click.stop='logOn()')
    md-tab(md-label='Docs'
           href='https://docs.prayerjournal.me'
           target='_blank'
           @click.stop='')
</template>

<script>
'use strict'

import { mapState } from 'vuex'

export default {
  name: 'navigation',
  data () {
    return {}
  },
  computed: {
    hasSnoozed () {
      return this.isAuthenticated &&
        Array.isArray(this.journal) &&
        this.journal.filter(req => req.snoozedUntil > Date.now()).length > 0
    },
    ...mapState([ 'isAuthenticated', 'journal' ])
  },
  methods: {
    logOn () {
      this.$auth.login()
    },
    logOff () {
      this.$auth.logout(this.$store, this.$router)
    }
  }
}
</script>
